config/routes.rb
Dragndrop::Application.routes.draw do
  resources :pieces

end

app/models/piece.rb
class Piece < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pieces_controller.rb
class PiecesController < ApplicationController
  # GET /pieces
  # GET /pieces.json
  def index
    @pieces = Piece.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pieces }
    end
  end

  # GET /pieces/1
  # GET /pieces/1.json
  def show
    @piece = Piece.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/new
  # GET /pieces/new.json
  def new
    @piece = Piece.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @piece }
    end
  end

  # GET /pieces/1/edit
  def edit
    @piece = Piece.find(params[:id])
  end

  # POST /pieces
  # POST /pieces.json
  def create
    @piece = Piece.new(params[:piece])

    respond_to do |format|
      if @piece.save
        format.html { redirect_to @piece, notice: 'Piece was successfully created.' }
        format.json { render json: @piece, status: :created, location: @piece }
      else
        format.html { render action: "new" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pieces/1
  # PUT /pieces/1.json
  def update
    @piece = Piece.find(params[:id])

    respond_to do |format|
      if @piece.update_attributes(params[:piece])
        format.html { redirect_to @piece, notice: 'Piece was successfully updated.' }
        format.json { render json: @piece }
      else
        format.html { render action: "edit" }
        format.json { render json: @piece.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pieces/1
  # DELETE /pieces/1.json
  def destroy
    @piece = Piece.find(params[:id])
    @piece.destroy

    respond_to do |format|
      format.html { redirect_to pieces_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pieces_helper.rb
module PiecesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dragndrop</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pieces/_form.html.erb
<%= form_for(@piece) do |f| %>
  <% if @piece.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@piece.errors.count, "error") %> prohibited this piece from being saved:</h2>

      <ul>
      <% @piece.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :color %><br />
    <%= f.text_field :color %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pieces/edit.html.erb
<h1>Editing piece</h1>

<%= render 'form' %>

<%= link_to 'Show', @piece %> |
<%= link_to 'Back', pieces_path %>

app/views/pieces/index.html.haml
%h1 Change color by dragging and dropping 

- @pieces.each do |piece|
  .pc{:class => piece.color, :data => {:type => "piece", :id => piece.id, :color => piece.color}}
    Piece
    = piece.id
#colors
  .color_square{:class => "white", :data => {:color => "white"}}
  .color_square{:class => "black", :data => {:color => "black"}}
  .color_square{:class => "blue", :data => {:color => "blue"}}
  .color_square{:class => "green", :data => {:color => "green"}}
#links
  = link_to 'New Piece', new_piece_path

app/views/pieces/new.html.erb
<h1>New piece</h1>

<%= render 'form' %>

<%= link_to 'Back', pieces_path %>

app/views/pieces/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Color:</b>
  <%= @piece.color %>
</p>


<%= link_to 'Edit', edit_piece_path(@piece) %> |
<%= link_to 'Back', pieces_path %>